---
title: "STATISTICS 648: Homework #1"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
  
---

```{r setup, include=FALSE}
library(flexdashboard)
library(htmltools)
```

Solution 1 {data-navmenu="Solutions 1-8"}
=====================================
Column {data-width=1000}
-----------------------------------------------------------------------

### R Notebook

```{r}
includeHTML("HW1_RNB.html")
```


Solution 3 {data-navmenu="Solutions 1-8"}
=====================================  
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Solution 5 {data-navmenu="Solutions 1-8"}
=====================================  




Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Solution 9 {data-navmenu="Solutions 9-13"}
=====================================




Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Solution 10 {data-navmenu="Solutions 9-13"}
=====================================  




Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Solution 12 {data-navmenu="Solutions 9-13"}
=====================================  




Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Solution 13 {data-navmenu="Solutions 9-13"}
=====================================  




Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Solution 15 {data-navmenu="Solutions 14-21"}
=====================================  




Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Solution 17 {data-navmenu="Solutions 14-21"}
=====================================  




Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

Solution 21 {data-navmenu="Solutions 14-21"}
=====================================  




Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```